# Generated by Django 6.0.3 on 2026-03-10 09:54

import django.core.validators
import wiki.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3)])),
                ('tier', models.CharField(choices=[('Inicial', 'Inicial'), ('Épico', 'Épico'), ('Legendario', 'Legendario'), ('Mítico', 'Mítico')], max_length=15)),
                ('slot_type', models.CharField(choices=[('Daño', 'Daño'), ('Defensa', 'Defensa'), ('Utilidad', 'Utilidad')], max_length=15)),
                ('gold_cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(300)])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(30)])),
                ('image_url', models.URLField(validators=[wiki.models.validate_https_url])),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('short_code', models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(2), wiki.models.validate_uppercase_code])),
                ('capital', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('faction', models.CharField(choices=[('Imperio', 'Imperio'), ('Reino', 'Reino'), ('Ciudad estado', 'Ciudad estado'), ('Tribu', 'Tribu'), ('Territorio mágico', 'Territorio mágico')], max_length=20)),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(40)])),
                ('image_url', models.URLField(validators=[wiki.models.validate_https_url])),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(2)])),
                ('title', models.CharField(max_length=80, validators=[django.core.validators.MinLengthValidator(4)])),
                ('role', models.CharField(choices=[('Asesino', 'Asesino'), ('Luchador', 'Luchador'), ('Mago', 'Mago'), ('Tirador', 'Tirador'), ('Soporte', 'Soporte'), ('Tanque', 'Tanque')], max_length=15)),
                ('resource_type', models.CharField(choices=[('Mana', 'Mana'), ('Energía', 'Energía'), ('Furia', 'Furia'), ('Sin recurso', 'Sin recurso')], max_length=15)),
                ('release_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2009), wiki.models.validate_not_future_year])),
                ('lore', models.TextField(validators=[django.core.validators.MinLengthValidator(60)])),
                ('image_url', models.URLField(validators=[wiki.models.validate_https_url])),
                ('featured_items', models.ManyToManyField(blank=True, related_name='champions', to='wiki.item')),
                ('regions', models.ManyToManyField(related_name='champions', to='wiki.region')),
            ],
        ),
    ]
